apiVersion: v1
kind: Service
metadata: 
  name: frontend
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: {{ include "common.containerPort" . }}
    protocol: TCP
  type: {{ .Values.service.type }}
  selector:
    {{- include "common.labels" . | nindent 4 }}
