replicas: 1
image: "postgres:latest"
usernameSecret:
  name: "postgres-sec"
  key: "username"
passwordSecret:
  name: "postgres-sec"
  key: "password"
database: "mydatabase"
volumeMountPath: "/var/lib/postgresql/data"
pvc:
  claimName: "postgres-volume-claim"
resources:
  requests:
    memory: "512Mi"
    cpu: "500m"
  limits:
    memory: "1Gi"
    cpu: "1"
PostgreSQL:
  hostpath: /data/postgres
