apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "postgres.fullname" . }}-deployment
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "postgres-deployment.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "postgres-deployment.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.image }}"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.usernameSecret.name }}
                  key: {{ .Values.usernameSecret.key }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.passwordSecret.name }}
                  key: {{ .Values.passwordSecret.key }}
            - name: POSTGRES_DB
              value: {{ .Values.database }}
          volumeMounts:
            - name: postgres-volume
              mountPath: {{ .Values.volumeMountPath }}
      volumes:
        {{- include "postgres-deployment.volume" . | nindent 6 }}
      resources:
        requests:
          memory: {{ .Values.resources.requests.memory }}
          cpu: {{ .Values.resources.requests.cpu }}
        limits:
          memory: {{ .Values.resources.limits.memory }}
          cpu: {{ .Values.resources.limits.cpu }}

