apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.fullname" . }}-sec
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  password: {{ .Values.passwordSecret.password | printf "%s" | b64enc }}
  username: {{ .Values.usernameSecret.username | printf "%s" | b64enc }}

