apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "postgres.fullname" . }}-svc
spec:
  selector:
    {{- include "postgres-deployment.selectorLabels" . | nindent 4 }}
  ports:
  - name: postgres
    protocol: TCP
    port: 5432
    targetPort: 5432
  type: LoadBalancer
