apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress
  labels:
    {{- include "common.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 | trimSuffix "\n" }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  defaultBackend:
    service:
      name: {{ .Chart.Name }}-nodeport-service
      port:
        number: 80

